name: Manually push changes to another environment

permissions:
  id-token: write # This is required for requesting the JWT
  contents: write # This is required for actions/checkout

on:
  workflow_dispatch:
    inputs:
      deploy_to:
        description: "Environment/branch to deploy to"
        required: true
        default: staging
        type: choice
        options:
          - staging
          - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure all history is fetched to enable rebasing and merging
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Set up Git user
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

      - name: Push to staging
        if: ${{ github.event.inputs.deploy_to == 'staging' }}
        run: |
          git fetch origin staging
          git checkout develop
          git rebase origin/staging
          git checkout origin/staging
          git merge --ff-only develop
          git push origin HEAD:staging

      - name: Push to main
        if: ${{ github.event.inputs.deploy_to == 'main' }}
        run: |
          git fetch origin main
          git checkout staging
          git rebase origin/main
          git checkout origin/main
          git merge --ff-only staging
          git push origin HEAD:main
